### ISSUE TITLE
[QUESTION] webERP vs KwaMoja

### ISSUE THREAD

**Issue by the-liquid-metal** [timschofield/webERP#205]
Hello.

Recently i found [KwaMoja](https://github.com/timschofield/KwaMoja).

1. Which one is the successor of the other?
2. What is the status of each project (still in development, discontinued)?
3. Are there any plans to use popular frameworks/library (laravel, symfony, Vue, React, etc)?
4. Are there any plans to use recent php version?

**Comment by timschofield** [comment]
Hello Hendra, I initially started KwaMoja at a time when my access to webERP was blocked. I now have got control of webERP back, and am busy porting all the KwaMoja improvements I did back to webERP. So the answer to questions 1 and 2 is that soon there will be no difference.
The answer to question 3 is no. The design philosophy of webERP remain unchanged. I believe that philosophy has been shown to work well for over 20 years. I realise many will disagree with this statement but that is what is great about Free/open source software.
As for 4, the master branch on this repository is mostly PHP8 compatible. There are just a few things I am working on before I can say categorically it is PHP8 compatible.

Hope this helps,
Tim

**Comment by the-liquid-metal** [comment]
> ... The design philosophy of webERP remain unchanged. ...
> 

I'm interested in this one. Can you explain it in more detail?

**Comment by timschofield** [comment]
Both Phil and I are accountants, with no background in coding, other than as a hobby. It was designed to be simple to understand, so that businesses could make their own changes, without a need for deep coding knowledge. Also the directory structure was intended to be very shallow. In general it was designed so that you can easily find your place in the code.
For example, if you are entering a GL journal you can see from the browser you are using GLJournal.php. Opening that file you can see all the logic involved in entering and processing a journal (there are a few includes, for session managemnt, header and footer).
We have always understood this breaks best practice but we have found over the last 20 years that businesses have been able to fairly easily modify the scripts for their own use.

Tim

**Comment by the-liquid-metal** [comment]
Thanks for the explanation.

I have known webERP for a long time. However, because my work has nothing to do with this kind of app, and webERP is a fairly complicated application, my knowledge of webERP is still very limited.

Hopefully i can contribute to this project.
