### ISSUE TITLE
Your Composer dependencies require a PHP version ">= 8.1.0"

### ISSUE THREAD

**Issue by andrewcouling** [timschofield/webERP#291]
The new installer seems to run successfully, then I get an almost blank page with the following message:

>Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".

I am running PHP version: 7.4
The latest code is backward compatible, right?

**Comment by aingelc12ell** [comment]
PHP Composer is required for the libraries stored in the /vendor directory.

Backward compatibility should be kept to minimum to allow more efforts for newer and more secure features. This will allow all of us to cope up with others while we can dedicate more time to update rather than long-term maintenance.

**Comment by andrewcouling** [comment]
Thanks for the explanation @aingelc12ell.
We'll need to update the minimum requirements in README.md before too long, so can include PHP 8.1 in this.
